# Generated by Django 4.2.7 on 2024-11-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="plagiarism_report",),
        migrations.AddField(
            model_name="project",
            name="most_similar_project",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
