# Generated by Django 4.2.7 on 2024-11-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="most_similar_project",
            new_name="most_similar_code_project",
        ),
        migrations.RemoveField(model_name="project", name="plagiarism_score",),
        migrations.AddField(
            model_name="project",
            name="most_similar_report_project",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="plagiarism_score_code",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="plagiarism_score_report",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="uploaded_report",
            field=models.FileField(blank=True, null=True, upload_to="uploads/reports/"),
        ),
        migrations.AddField(
            model_name="project",
            name="uploaded_zip",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/code_zips/"
            ),
        ),
    ]
