# Generated by Django 4.2.7 on 2024-11-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0004_rename_most_similar_project_project_most_similar_code_project_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="code_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="report_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
