# Generated by Django 4.2.7 on 2024-11-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_code_text_project_report_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="most_similar_project",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="plagiarism_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
