# Generated by Django 4.2.7 on 2024-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0004_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/messages/"
            ),
        ),
        migrations.AlterField(
            model_name="message", name="text", field=models.TextField(blank=True),
        ),
    ]
