# Generated by Django 4.2.7 on 2024-11-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0005_message_file_alter_message_text"),
    ]

    operations = [
        migrations.DeleteModel(name="File",),
    ]
